Closing dangling file pointers
jensengroup/propka pull request #132
Opened 2021-10-29 09:56 UTC by stefdoerr

Hi, I was getting lots of warnings about open file pointers so I thought I'd make this PR to resolve the warnings. Also I assume eventually you might hit OS issues if you open too many files while using propka programmatically through python.

2021-10-31 14:36 UTC, sobolevnrm requested changes

2021-10-31 14:36 UTC, sobolevnrm commented on propka/input.py
> +    if not stream:
Couldn't this be done more cleanly by either checking for duck-typed attributes or simply using `isinstance`?

2021-10-31 17:34 UTC, speleo3 commented
How about solving this with a context manager (and removing the ["TODO - convert this to a context manager"](https://github.com/jensengroup/propka/blob/68007f065c5400566598509875344ed1c0f593c9/propka/input.py#L22) comment)? If you don't mind, I can open a pull request with the solution I have in mind, but I'd also be happy to review yours if you want to give it a try.

2021-10-31 21:53 UTC, intendo commented
> How about solving this with a context manager (and removing the ["TODO - convert this to a context manager"](https://github.com/jensengroup/propka/blob/68007f065c5400566598509875344ed1c0f593c9/propka/input.py#L22) comment)? If you don't mind, I can open a pull request with the solution I have in mind, but I'd also be happy to review yours if you want to give it a try.

I would vote for the context manager approach.

2021-11-01 07:07 UTC, stefdoerr commented
Sure feel free to open another PR!

2021-11-01 07:21 UTC, closed without merging